### PR TITLE
Add support for sparse arrays

### PR DESCRIPTION
**Pull request by Webifi**

### CODE REVIEW

**Comment by NeilFraser** [comment]
Can you sign the Google CLA?  https://cla.developers.google.com/
Thanks!

**Comment by Webifi** [comment]
Signed.

Looking over how it's interpreted, it appears `i in o` would perform better in the interpreter than `o.hasOwnProperty(i)`.   Since you were already using `i in o` in the iterators (forEach, etc.), I just changed to that as well.

**Comment by cpcallen** [comment]
> Looking over how it's interpreted, it appears `i in o` would perform better in the interpreter than `o.hasOwnProperty(i)`.

It is also more correct: for instance, [in the spec](https://tc39.es/ecma262/#sec-array.prototype.shift) `shift` is defined in terms of HasProperty rather than _HasOwnProperty_, so inherited properties are not ignored when determining how to deal with spare arrays.

This does lead to some slightly surprising behaviour, e.g.:

```
Welcome to Node.js v16.0.0.
Type ".help" for more information.
> var arr = [0,,,,,,,7];
undefined
> Object.setPrototypeOf(arr, [,,2]);
[ 0, <6 empty items>, 7 ]
> arr.join()
'0,,2,,,,,7'
> arr.shift();
0
> arr
[ <1 empty item>, 2, <4 empty items>, 7 ]
> arr.join()
',2,2,,,,7'
> arr.shift();
undefined
> arr
[ 2, 2, <3 empty items>, 7 ]
> arr.join()
'2,2,2,,,7'
```

**Review by cpcallen — APPROVED** [review]

**Comment by NeilFraser** [comment]
Comparative tests of all functions look good:

```
var a = [,,,7];
a.shift();
Was: [undefined, undefined, 7]
Now: [empty × 2, 7]

var a = [,,,7];
a.unshift(undefined, undefined);
Was: [undefined, undefined, undefined, undefined, undefined, 7]
Now: [undefined, undefined, empty × 3, 7]

var a = [,,,7];
a.reverse();
Was: [7, undefined, undefined, undefined]
Now: [7, empty × 3]

var a = [,,,7];
a.slice(1, 99);
Was: [undefined, undefined, 7]
Now: [empty × 2, 7]

var a = [,,,7];
a.splice(1, 1, undefined);
Was: [undefined]  and  [empty, undefined, undefined, 7]
Now: [empty]  and  [empty, undefined, empty, 7]

[,,,7].concat([8,,,], 9);
Was: [undefined, undefined, undefined, 7, 8, undefined, undefined, 9]
Now: [empty × 3, 7, 8, empty × 2, 9]

[,,,7].join(9);
Was: 'undefined9undefined9undefined97'
Now: '9997'

[,,,7].sort()
Was: [7, undefined, undefined, undefined]
Now: [7, empty × 3]
```

Excellent!

**Pull request merged**
